# Generated by Django 6.0.4 on 2026-05-01 20:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p', models.FloatField()),
                ('f', models.FloatField()),
                ('size', models.IntegerField()),
                ('grid', models.JSONField()),
                ('steps', models.IntegerField(default=0)),
                ('fire_histogram', models.JSONField(default=list)),
            ],
        ),
    ]
